"""Pydantic schemas for request/response payloads.

Description: Defines data models used by the API for validation and serialization.
"""

from pydantic import BaseModel, Field


class ItemCreate(BaseModel):
    """Payload for creating a new item."""
    # Name to assign to the new item; validated for length constraints
    name: str = Field(min_length=1, max_length=255)


class ItemRead(BaseModel):
    """Public representation of an item returned by the API."""
    # Autogenerated database identifier
    id: int
    # Item name as stored in the database
    name: str

    class Config:
        # Enable creation from ORM instances (SQLAlchemy models)
        from_attributes = True


